title: Praveen Kumar
logo: https://drive.google.com/file/d/1JwQ5XZxZTG853iMllv4cnN-55e5VTBYG/view?usp=sharing
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
